# Generated by Django 5.1.1 on 2024-10-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_icono_alter_curso_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.CharField(blank=True, help_text='Formato: P1-401 (Pabellón 1, Piso 4, Aula 401)', max_length=100, null=True),
        ),
    ]
